### ISSUE TITLE
App Search containing trailing whitespace fails using get_app but succedes using Alteryx Interactive API dos

### ISSUE THREAD

**Issue by oli666** [mtreadwell/alterryx#3]
Hi Michael,

I am using the following as request_params (pls note the space at the end of the search term): 

`structure(list(packageType = "0", search = "API_1 "), .Names = c("packageType", 
"search"))`

"get_app()" fails using the above request_params: 

__Error in check_status(response) : 
  401 UnauthorizedException The provided signature(oauth_signature) is invalid.__

I have also tried to use the escape sequence for a blank, %20, but that did not work either: 

`structure(list(packageType = "0", search = "API_1%20"), .Names = c("packageType", 
"search"))`

I guess somehow the construction of the API call URL gets corrupted by the tailing whitespace. 

Interesting side notes:

I can, however, use "API_1 " within the API docs of the Gallery. I have verified that for Alteryx Gallery 11.0 and 11.3 

Obviously, on our 11.0 server there is something wrong with the Lucene search engine. The effect is, that using the Alteryx API docs we DO NOT get results for "API_1" but we DO for "API_1 " (including the whitespace). 

Oli

**Comment by mtreadwell** [comment]
This was an issue with my url encoding and has been fixed in the master branch. Thanks so much for reporting this, I appreciate it.
