### ISSUE TITLE
No valid Job Output even with plain Alteryx Text Input mapped to plain Altery Output tool

### ISSUE THREAD

**Issue by oli666** [mtreadwell/alterryx#4]
I am having issues getting a valid output using "get_job_output". I have tried a rather basic scenario by using a plain Alteryx input tool to create a table with column names and one row. Then an output tool is used to produce either an Alteryx database file or a csv file. However, both file formats trigger a warning when using "get_job_output". 
The output sublist looks as follows: 

$ outputs    :List of 2
  ..$ :List of 3
  .. ..$ id     : chr "5a78701b4fe3a58a969533c6"
  .. ..$ formats:List of 1
  .. .. ..$ : chr "Raw"
  .. ..$ name   : chr "output"
  ..$ :List of 3
  .. ..$ id     : chr "5a78701b4fe3a58a969533c7"
  .. ..$ formats:List of 1
  .. .. ..$ : chr "Raw"
  .. ..$ name   : chr "test.csv"

Any glue what might be the root cause for that?

**Comment by mtreadwell** [comment]
The function `get_job_output` will generate a warning if a single output isn't _.yxdb_ or _.csv_, even if there are other valid inputs. For example, if my application has three outputs: two _.csv_ and one _.xlsx_, a warning will be generated and the output from the two _.csv_ files will be read into R as a list of data frames.

Question, when you run the app in Alteryx Gallery, what does your output list show?

![image](https://user-images.githubusercontent.com/10984846/35814152-f7e14ace-0a5a-11e8-81f8-6f2e1eec3a0c.png)

**Comment by oli666** [comment]
This is the ouput in the Gallery. 

 



The actual content is: 

 

one,two

1,2

 

It seems not to be read into R as a data frame; only the meta information gets read in as shown in my posting.

**Comment by oli666** [comment]
I guess I have found the issue. According to the documentation, two **file types**, csv and yxdb, are said to be supported by the function "get_job_output" to render a "data frame"-style output. However, having an output tool in the app that returns a csv file does NOT do the trick: A **csv file (type)** is obviously not tagged as **file format** "Csv" but rather just as "Raw". (see output item "output2.csv" below). 
Only an output tool configuered to produce a yxdb file does the job for me as it contains "Csv" in the list of output formats (first output item below). 
Don't know if that is a version specific issue (I am using 11.0); if not, you might want to point to the fact that only Alteryx yxdb files are supported for the "get_job_output" function. 

```R
{
      "id": "5a869354a78d1d47a855b966",
      "formats": [
        "Shp",
        "Tab",
        "Mif",
        "Dbf",
        "Csv",
        "Raw",
        "Tde"
      ],
      "name": "output.yxdb"
    },
    {
      "id": "5a869354a78d1d47a855b967",
      "formats": [
        "Raw"
      ],
      "name": "output2.csv"
    }
```
